# this dockerfile is used to build a docker image for nginx
# and manually changes the content of the index.html file


FROM nginx:1.27.0

RUN apt-get update 
RUN apt-get install -y vim
RUN apt-get install -y curl

